version: "3.8"
services:
  talkrobot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: electronic_talkrobot_container
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # 使用 1 张显卡，或者用 'all'
              capabilities: [gpu]
    volumes:
      - E:\Research Training\embedding_model:/data/embedding_model
      - E:\Research Training\knowledgebase:/data/knowledgebase
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
      - KNOWLEDGEBASE_PATH=/data/knowledgebase
      - JINA_EMBEDDINGS_V2_BASE_ZH_PATH=/data/embedding_model/jina-embeddings-v2-base-zh/jina-embeddings-v2-base-zh
      - JINA_EMBEDDINGS_V2_BASE_ZH_DIMENSION=768
      - RAG_INIT_FLAG=false

    env_file:
      - ./backend/.env

    command: uvicorn backend.server:app --host 0.0.0.0 --port 8000 --reload
